### PR TITLE
Made plugin translatable; added German translation; tweaked stylesheet

### PR DESCRIPTION
**Pull request by MarcelvC**

### CODE REVIEW

**Comment by bramley** [comment]
This plugin is a bit different to the other ones. They were developed for phplist 2 which did not have much support for plugins and translations. That is why I had to develop my own method, similar but separate to the way that phplist does translations.

The Segment plugin was designed for phplist 3 which in theory has support for plugins providing translations. That is why a number of strings are wrapped by the s() function. The translation method does not work yet but I added calls to s() in anticipation of it working sometime. I'm not sure that I want to use the old approach for this plugin.
I will enquire about the translation functionality and when it might be working, but in the meantime don't do any more of this. I do appreciate what you have done so far.
Thanks

**Comment by MarcelvC** [comment]
I see, thanks for letting me know! I needed a quick solution for the installation we're currently using and thought I might as well share it. Don't want to bother you though.

**Comment by MarcelvC** [comment]
Any news on when the translation functionality of phplist might be ready?

**Comment by bramley** [comment]
Sorry but I haven't followed up about this. 
It will probably be best if you can raise an issue about translating the text within plugins on Mantis https://mantis.phplist.org/view_all_bug_page.php

I had a quick look and cannot see any current issue regarding translation, so doing this will bring it to the attention of the developer.

**Comment by MarcelvC** [comment]
Have you heard anything new about the phplist core providing support for the translation of plugins?

I haven't filed a bug report (as you suggested a year ago) since I unfortunately lack the knowledge and insight to report what would have to be done specifically.

**Comment by bramley** [comment]
Closing due to no response.

**Pull request closed without merging**
